### ISSUE TITLE
No automated tests

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-dotnet#11]
No automated tests makes vetting pull requests even more time consuming.

I noticed your comment @stevespringett on another issue that you aren't a .net developer. I'm opening this issue to find out if you want a .net developer to jump in and work on this.

It would be a bit of effort to implement, and review. So please let me know if you are interested. Although I do have a bit of free time over the next couple of days so I'll probably make a start on it anyway.

**Comment by stevespringett** [comment]
Agreed. Any help is good help. I don't personally have a need for .NET, but there obviously is a community need for it. The code that's in the repo currently was hacked together and ported from a similar project. I'm also using Visual Studio on macOS which is interesting...

But yes, if you or anyone on your team is able to contribute to the project, it would help tremendously.

**Comment by patros** [comment]
Cool. It will involve a fair bit of refactoring so I’ll try to break it up into a series of smaller, easier to digest, chunks of work.
