### ISSUE TITLE
.NET 4 support

### ISSUE THREAD

**Issue by mattmedus** [CycloneDX/cyclonedx-dotnet#136]
Hi I was wondering if CycloneDX-dotnet supports scanning the classic .NET 4 framework instead of .NET CORE. I'm able to run it on the project *.sln but I'm not getting any dependencies as a result.
Any ideas?

**Comment by coderpatros** [comment]
Hi @mattmedus the tool does work with full framework projects that use packages.config files.

Specifying the solution file should work, but you can also specify the top level directory and it will recursively scan for packages.config files.

**Comment by coderpatros** [comment]
@mattmedus did you get it working?

**Comment by coderpatros** [comment]
I'm going to close this issue, but feel free to re-open it with more detail if you are still having issues.
