### ISSUE TITLE
Hardcoded timeout limit for dotnet command leads to problems with debugging

### ISSUE THREAD

**Issue by oxdef** [CycloneDX/cyclonedx-dotnet#147]
Steps to reproduce:
1. See that sometimes `cyclonedx-dotnet` returns `Dotnet restore failed:` and so can't make result bom file
2. In same case when run it pair with  `dotnet restore` command everything is ok

Current result:
`dotnet restore` is called inside `cyclonedx-dotnet` in [DotnetUtilsService.cs](https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/CycloneDX.Core/Services/DotnetUtilsService.cs)
```csharp
        public DotnetUtilsResult Restore(string path)
        {
            var arguments = "restore";
            if (!string.IsNullOrEmpty(path)) arguments = $"{arguments} \"{path}\"";

            var commandResult = _dotnetCommandService.Run(arguments);

            if (commandResult.Success)
            {
                return new DotnetUtilsResult();
            }
            else
            {
                return new DotnetUtilsResult
                {
                    // dotnet restore only outputs to std out, not std err
                    ErrorMessage = commandResult.StdOut
                };
            }
        }
```
If look on [dotnetCommandService.Run](https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/CycloneDX.Core/Services/DotnetCommandService.cs#L57)
```csharp
public DotnetCommandResult Run(string workingDirectory, string arguments)
        {
            var psi = new ProcessStartInfo(DotNetExe.FullPathOrDefault(), arguments)
            {
                CreateNoWindow = true,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                WorkingDirectory = workingDirectory
            };
            
            using (var p = Process.Start(psi))
            {
                var exitCode = 0;
                // ...
                var processExited = p.WaitForExit(60000);
                if (processExited)
                {
                    exitCode = p.ExitCode;
                }
                else
                {
                    p.Kill();
                    exitCode = -1;
                }
                // ...
                return result;
            }
```
Here we see hard-limit for 60 sec to call `dotnet restore`. It could be not enough in some cases, e.g. when you need to download 400+ heavyweight dependencies 

Expected result:

1. Add option for `cyclonedx-dotnet` to change this time limit
2. Add error message to output about the limit passing event

**Comment by coderpatros** [comment]
Hi @oxdef, that timeout is too short. That's a carry over from when I was troubleshooting the command actually hanging.

What do you think is a reasonable timeout for normal usage? I'm thinking something like 5 minutes. Still short enough that it shouldn't hang a build for too long. But should be long enough for most cases.

I can pretty quickly change the default and push out a new release. And then can add an option to override the default later.

**Comment by oxdef** [comment]
Hi @coderpatros 

> What do you think is a reasonable timeout for normal usage? I'm thinking something like 5 minutes. Still short enough that it shouldn't hang a build for too long. But should be long enough for most cases.

Yes, 5 min looks as reasonable value. We use it as hard limit in CI/CD pipeline job for Dependency Track. 

> I can pretty quickly change the default and push out a new release. 

Great!

> And then can add an option to override the default later.

It will be also nice to add custom error message to output about the limit passing event.

**Comment by coderpatros** [comment]
@oxdef 5 minute timeout is in v0.10.5. I also added output to indicate the timeout has been hit. And in the case of the timeout occurring for a restore it also suggests running `dotnet restore` before `dotnet CycloneDX`

I'll leave this issue open though. It would still be beneficial to be able to override the default.

**Comment by oxdef** [comment]
@coderpatros Thanks for the quick fix!

**Comment by coderpatros** [comment]
@oxdef closing this issue. It isn't released yet. But will be in the next release.
