### ISSUE TITLE
Incorrect Version getting added in bom.xml

### ISSUE THREAD

**Issue by shounakitraj** [CycloneDX/cyclonedx-dotnet#15]
Hi Team,

I am using "dotnet-CycloneDX" package for creating bom.xml from .sln file. But as per my observation it is adding incorrect version in bom.xml. For example the .csproj file contains following entry:

`<PackageReference Include="WebGrease" version="1.6.0" />`

In above it is clear that the version of WebGrease is 1.6.0 but if we check the bom.xml it shows version 1.5.2 as follows:

```
    <component type="library">
      <name>WebGrease</name>
      <version>1.5.2</version>
      <description><![CDATA[Web Grease is a suite of tools for optimizing javascript, css files and images.]]></description>
      <licenses>
        <license>
          <url>http://www.microsoft.com/web/webpi/eula/msn_webgrease_eula.htm</url>
        </license>
      </licenses>
      <purl>pkg:nuget/WebGrease@1.5.2</purl>
    </component>
```

Also I have observed that it includes version of library which is not present either in .csproj or packages.config file.

For example:
packages.config file contains:
`<package id="WebGrease" version="1.6.0" targetFramework="net45" />`

but bom.xml file contains 2 entries for WebGrease one 1.6.0 and other with version 1.5.2 as shown below:

```
    <component type="library">
      <name>WebGrease</name>
      <version>1.5.2</version>
      <description><![CDATA[Web Grease is a suite of tools for optimizing javascript, css files and images.]]></description>
      <licenses>
        <license>
          <url>http://www.microsoft.com/web/webpi/eula/msn_webgrease_eula.htm</url>
        </license>
      </licenses>
      <purl>pkg:nuget/WebGrease@1.5.2</purl>
    </component>

    <component type="library">
      <name>WebGrease</name>
      <version>1.6.0</version>
      <description><![CDATA[Web Grease is a suite of tools for optimizing javascript, css files and images.]]></description>
      <licenses>
        <license>
          <url>http://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_ENU.htm</url>
        </license>
      </licenses>
      <purl>pkg:nuget/WebGrease@1.6.0</purl>
      <externalReferences>
        <reference type="website">
          <url>http://webgrease.codeplex.com/</url>
        </reference>
      </externalReferences>
    </component>
```
Could you please take a look into it and let me know if I am missing something?

**Comment by stevespringett** [comment]
Can you provide a project on GitHub that replicates the issue?

**Comment by shounakitraj** [comment]
Hi Steve,

Thanks for quick response, actually it is our internal project for which I am using cyclonedx to create bom.xml and send it to DT for Secure Composition Analysis.

So I cannot share directly the project, but if required I can share few lines of from the .csproj or packages.config file for verification.

Thanks again for quick response.

**Comment by stevespringett** [comment]
Feel free to send to steve.springett [at] owasp.org. As much info as you can provide will be helpful.

**Comment by shounakitraj** [comment]
Thanks, I have sent email with detailed observation. Please let me know if any more information is required.

**Comment by shounakitraj** [comment]
Hi Steve,

What I have understood from the issue is that whenever cycloneDX gets the version of library from packages.config file it also lists it's (found libraries') dependent libraries in bom.xml

For example my packages.config file contains:
"Microsoft.Azure.ActiveDirectory.GraphClient" Version="2.1.1"

But if we check the bom.xml it has following list:

```
Retrieving Microsoft.Azure.ActiveDirectory.GraphClient 2.1.1
Retrieving Microsoft.Data.Services.Client 5.6.4
Retrieving Microsoft.Data.Edm 5.6.4
Retrieving Microsoft.Data.OData 5.6.4
Retrieving System.Spatial 5.6.4
```

If I check the dependencies of Microsoft.Azure.ActiveDirectory.GraphClient it has list of above libraries as dependencies.
Ref: https://www.nuget.org/packages/Microsoft.Azure.ActiveDirectory.GraphClient

Due to this DT shows Microsoft.Data.OData as vulnerable library even if we are not using it explicitly.

Regards,
Shounak

**Comment by fatihersinadim** [comment]
Hi @stevespringett,

I think that the problem mentioned above is caused by including the dependencies of the libraries specified in "packages.config" by making a request similar to the following.

https://api.nuget.org/v3-flatcontainer/Microsoft.Azure.ActiveDirectory.GraphClient/2.1.1/Microsoft.Azure.ActiveDirectory.GraphClient.nuspec

This usage, does not always give correct results. For example, you can see the following address, these dependency libraries versions are minimums. 

https://www.nuget.org/packages/Microsoft.Azure.ActiveDirectory.GraphClient/

In other words, version 5.8.4 of the Microsoft.Data.Edm library may also be used in the project.

I think the following block of code can be removed to avoid false positives, what do you think?

https://github.com/CycloneDX/cyclonedx-dotnet/blob/21d0a9a8b1573b6b5566a4635611c413ef231b20/CycloneDX/Services/NugetService.cs#L127-L138

Regards,

**Comment by coderpatros** [comment]
@fatihersinadim you're on the right track about why incorrect versions are being returned. 

The existing behaviour is already incorrect, but transitive dependencies should be included in the BoM. So removing that code would still result in an incorrect BoM. But I don't know which approach is more/less incorrect :) and that could change from project to project.

I'm currently working on an alternative dependency resolution approach that will use dotnet restore logic #27 

That should fix this issue, and be correct.

**Comment by coderpatros** [comment]
@shounakitraj can you please try this again with v0.9.2 and let me know how you go?

**Comment by shounakitraj** [comment]
@coderpatros Sure will check and let you know. Thank you for update

**Comment by coderpatros** [comment]
@shounakitraj going to close this issue. Feel free to re-open it if you are still getting incorrect versions in your bom.xml with the latest version.
