### ISSUE TITLE
Support net5

### ISSUE THREAD

**Issue by AnFa1978** [CycloneDX/cyclonedx-dotnet#281]
Does somebody in this project and community is working on net5 compatibility? It's clear that it's not supported until now from project home page. But raising issue to get fast feedback was idea. Thanks for your feedback in advance

**Comment by coderpatros** [comment]
@AnFa1978 I was actually planning on releasing .NET 5 support tonight now that it has been officially released. But if you wanted to have a go at raising a pull request for this that would be welcome too. I have a few things to add .NET 5 support to.

**Comment by coderpatros** [comment]
@AnFa1978 this has been released now (although sometimes it can take a while for nuget to index new package versions).
