### ISSUE TITLE
Licenses are not downloaded

### ISSUE THREAD

**Issue by SS-TT** [CycloneDX/cyclonedx-dotnet#30]
I've opened an issue on Dependency-Track and I've been asked to move it here.
Here's the link: DependencyTrack/dependency-track#510

**Comment by stevespringett** [comment]
As noted in https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl, licenseUrl is deprecated. However, it continues to be widely used. 

The CycloneDX .NET implementation does not download the license file or attempt to identify it. It might be interesting to use the GitHub API to determine the open source license. They already have logic to identify ab out a dozen licenses (and small variances such as copyrights in MIT).

**Comment by coderpatros** [comment]
It would be good to do this for opensource.org licence URLs too. It looks like, most of the time, the SPDX ID is in the URL. Maybe a way to implement this would be to extract the ID from the URL and cross reference it with the list of actual SPDX IDs?

**Comment by coderpatros** [comment]
We have 600 references to the Apache licence URLs in our BoMs. So even a simple match on URL could be useful.

**Comment by coderpatros** [comment]
Can this issue be closed now @SS-TT ?

**Comment by SS-TT** [comment]
Sure, sorry for missing that.
