### ISSUE TITLE
Wrong CycloneDX version is shown

### ISSUE THREAD

**Issue by patspaeth** [CycloneDX/cyclonedx-dotnet#362]
When I check the binary version I will see V1.0.0.0 but I expect 1.4.0.0
![image](https://user-images.githubusercontent.com/80386770/111443460-ae150280-8709-11eb-9d6f-d21be0521251.png)

**Comment by bdeman95** [comment]
We have the same issue on our side. Attached is an example.
![image](https://user-images.githubusercontent.com/68237904/117158936-daeea900-ad8d-11eb-9ac4-5745ddc4e92f.png)

**Comment by derekpuff** [comment]
I would also like to add that it would be helpful to have a command line option `--version` or some other method (such as part of the `--help` message) that would report the application version.

**Comment by coderpatros** [comment]
Now fixed in v1.6.1 with `--version` option too
