### ISSUE TITLE
dotnet CycloneDX -? exited with code 1

### ISSUE THREAD

**Issue by SaravananWipro** [CycloneDX/cyclonedx-dotnet#364]
I have installed CycloneDX in my windows system "dotnet tool install --global CycloneDX" and able to generate BOM report. 

I need to use this package for TFS build server for .net projects, I cannot install on server but the same time I need to used this package and execute commands through .targets from projects. I have downloaded "cyclonedx.1.3.0.nupkg" and extracted to create as packages, and included in global package folder. when I try to call below target from TFS build, getting error (exited with code 1). Could you please help the correct way to integrate with TFS build server and execute from .targets?

  <Target Name="CreateSBOM">
	<Exec Command="dotnet CycloneDX -?" />
    <Exec Command="dotnet CycloneDX ..\Components -o ..\Components" />
  </Target>

**Comment by SaravananWipro** [comment]
<Target Name="CreateSBOM">
	<Exec Command="dotnet CycloneDX -?" />
    <Exec Command="dotnet CycloneDX ..\Components -o ..\Components" />
  </Target>

I used above target to call from tfs build

**Comment by coderpatros** [comment]
I haven't used it on TFS. But does something like this work?

```
dotnet tool install --tool-path cyclonedx CycloneDX
./cyclonedx/dotnet-CycloneDX
```

**Comment by SaravananWipro** [comment]
> I haven't used it on TFS. But does something like this work?
> 
> ```
> dotnet tool install --tool-path cyclonedx CycloneDX
> ./cyclonedx/dotnet-CycloneDX
> ```

Thanks for the suggestion, but this trying to download from internet. Basically, i want install/restore CycloneDx with offline package at build time.

**Comment by coderpatros** [comment]
This might work. Say you have the nupkg file available under the directory `./packages`

```
dotnet tool install --tool-path cyclonedx CycloneDX --version 1.3.0 --add-source ./packages
./cyclonedx/dotnet-CycloneDX
```

**Comment by SaravananWipro** [comment]
> This might work. Say you have the nupkg file available under the directory `./packages`
> 
> ```
> dotnet tool install --tool-path cyclonedx CycloneDX --version 1.3.0 --add-source ./packages
> ./cyclonedx/dotnet-CycloneDX
> ```

I tried "dotnet tool install --tool-path cyclonedx CycloneDX --version 1.3.0 --add-source ./packages" on my local system, it did not recognized the "--version" and i removed version and it installed 1.4.0 whereas i have given package path for 1.3.0. The same command i tried on tfs server, its trying to access internet and getting "error : Unable to load the service index for source https://api.nuget.org/v3/index.json."
