### ISSUE TITLE
Support for hashes

### ISSUE THREAD

**Issue by jakrivan** [CycloneDX/cyclonedx-dotnet#375]
Are there any plans to support populating hashes for components in SBOM?
While it's allowed by standard not to have those in SBOM, they are necessary for validating integrity.

Thanks
Jan

**Comment by coderpatros** [comment]
Certainly is. But we’re busy with the release of v1.3 of the spec at the moment. 

But I’d like to support component level hashes by default. And opt in to include package files and hashes too. 

Pull requests are welcome too 😉

**Comment by jakrivan** [comment]
PR is a good idea - I'm on it now

**Comment by jakrivan** [comment]
https://github.com/CycloneDX/cyclonedx-dotnet/pull/376

**Comment by coderpatros** [comment]
Available in v1.5.0
