### ISSUE TITLE
Add support for paket (paket.lock files)

### ISSUE THREAD

**Issue by JanKrivanek** [CycloneDX/cyclonedx-dotnet#381]
[Paket](https://fsprojects.github.io/Paket/index.html) is alternative dependency manager for .NET. There is currently no support for generating SBOM files for Paket managed dependencies - it would be great to have it.

**Comment by coderpatros** [comment]
Hi @jakrivan I haven't used Paket myself.

Are all dependencies listed in the paket.lock file?

I'm not sure if it makes sense to add support to this tool or to take a copy of this tool and refactor to support Paket.

**Comment by jakrivan** [comment]
Yeah - that's a good question.
In our case we went different route (local resolve and then sbom generation). So this suggestion can be closed now or just kept around untill anybody needs it and then the discussion can happen.
