### ISSUE TITLE
Troubles with path

### ISSUE THREAD

**Issue by KOR-TEH** [CycloneDX/cyclonedx-dotnet#388]
Hi. Please, asking for some help.

Have problem with launching via docker. Trying to cmd command, as in instructions and got this:
![fff](https://user-images.githubusercontent.com/61863824/120354531-2ce20a80-c30b-11eb-9134-46520b38bb48.PNG)

**Comment by nscuro** [comment]
Hi @xXGeserXx, you need to mount `/home/xxx/deptrack/prj/edox` into the container first.

This should work:

```
$ sudo docker run --rm -v '/home/xxx/deptrack/prj/edox:/tmp/edox' cyclonedx/cyclonedx-dotnet -o /tmp/edox /tmp/edox
```

**Comment by xXGeserXx** [comment]
> Hi @xXGeserXx, you need to mount `/home/xxx/deptrack/prj/edox` into the container first.
> 
> This should work:
> 
> ```
> $ sudo docker run --rm -v '/home/xxx/deptrack/prj/edox:/tmp/edox' cyclonedx/cyclonedx-dotnet -o /tmp/edox /tmp/edox
> ```

Hi, thank you very much for your help, but i solved this problem:) But, i have new problem. Maybe, you know about:
![dddd](https://user-images.githubusercontent.com/61863824/120453875-11731000-c39c-11eb-8bc8-8af28c90c52e.PNG)

**Comment by coderpatros** [comment]
Hi @xXGeserXx can you share a minimal reproduction of this? Can probably just get away with just a sanitised version of your csproj file.

**Comment by xXGeserXx** [comment]
> Hi @xXGeserXx can you share a minimal reproduction of this? Can probably just get away with just a sanitised version of your csproj file.

Hi, well, first of all, i install clone dx through dotnet on CentOS 7. Then, i enter command dotnet CloneDX 'path to project folder' -o 'path to output folder'. Clone working sometime and then crash on this place. Everytime in this place.

**Comment by coderpatros** [comment]
Ah, that probably isn't the option you want. If you provide the project folder the tool looks for .NET full framework package.json files. For .NET core and .NET 5+ specify a solution or project file.
