### ISSUE TITLE
.net Project scan 

### ISSUE THREAD

**Issue by VASAVI512** [CycloneDX/cyclonedx-dotnet#394]
Hello,

We are looking for a tool which creates SBOM for both commercial and open source softwares.
CycloneDX captures/scans the commercial code and put in SBOM?
1. As i understood, to scan a .Net Projects we need to have a .sln, .config, etc.. as input file to genrate SBOM. Do we really need these files to scan a project, with out these files, can not we scan the directory?
2. SBOM can be created for a Binary files, like ,.dll or .jar, .war..? how we do we scan binary files.
Thanks in advance.

Regards,
Vasavi

**Comment by coderpatros** [comment]
This tool is designed to use the same package resolution method as the build process. So it won't work without the sln, csproj, etc files.

To create a list of components from a binary distribution you will need to use a software composition analysis tool. Noting that the results will be less accurate.

**Comment by VASAVI512** [comment]
Thank you Patrick. 
Any suggestions about the best Software composition analysis Tool.

**Comment by VASAVI512** [comment]
> This tool is designed to use the same package resolution method as the build process. So it won't work without the sln, csproj, etc files.
> 
> To create a list of components from a binary distribution you will need to use a software composition analysis tool. Noting that the results will be less accurate.

Hi Patrick,

Can you share CycloneDX supports how many languages to create SBOM

Regards,
Vasavi

**Comment by VASAVI512** [comment]
Hi Team,
   
Could you tell me how you are creating the SBOM from the .sln code, below is an example i have shared you to understand <license> Tag creation from source code.
I do not see the below type of license was not updated in Dependency Tracker Tool, why?.

Code downloaded from : https://github.com/aspnet/AspNetWebStack

 <component type="library">
      <publisher>Microsoft</publisher>
      <name>DotNetOpenAuth.AspNet</name>
      <version>4.0.3.12153</version>
      <description>Allow your web visitors to log into your web site using accounts they already have with popular services.</description>
      <hashes>
        <hash alg="SHA-512">8307767EF15610128D6F778DF0C349E025D6F68E818895C7042DFD998EC64483960DDAD48680D9DA6FED2CC44078FC630CA51DD6BD7916A4CAAC3443406DEF6A</hash>
      </hashes>
      <licenses>
        <license>
          <url>http://www.opensource.org/licenses/ms-pl.html</url>
        </license>
      </licenses>
      <purl>pkg:nuget/DotNetOpenAuth.AspNet@4.0.3.12153</purl>
      <externalReferences>
        <reference type="website">
          <url>http://www.dotnetopenauth.net/</url>
        </reference>
      </externalReferences>
    </component>

Regards,
Vasavi

**Comment by coderpatros** [comment]
Hi @VASAVI512 more general questions like these are probably better on the CycloneDX Slack workspace.

The AspNetWebStack project layout looks a bit complicated. You probably need to generate an SBOM for a particular project in that code base which represents the software you want to describe. But I'm not really familiar with that project.
