### ISSUE TITLE
Components of test projects should not be of scope required

### ISSUE THREAD

**Issue by patspaeth** [CycloneDX/cyclonedx-dotnet#415]
I would assume that the scope required is only for packages that will be required to run the application.
When I do not exclude test projects all components of these test projects are marked as required, but I would expect that they are marked as exclude or similar

**Comment by coderpatros** [comment]
Yeah, that should be the behaviour. The check is missing in the ProjectAssetsFileService.GetNugetPackages() method.

**Comment by patspaeth** [comment]
The question is: Shall all transitive dependencies be gathered or only the top level packages?
For me, the top level packages would be enough, what do you think?

**Comment by coderpatros** [comment]
Resolved in v1.6.2

**Comment by coderpatros** [comment]
Thanks for the PR @patspaeth
