### ISSUE TITLE
Add support for filtering test projects in solution files

### ISSUE THREAD

**Issue by cmenzi** [CycloneDX/cyclonedx-dotnet#43]
When specifying a `.sln` file, which usually includes production and tests projects, it should be possible to pass a `--include <regex>` or `--exclude <regex>` to filter out .Tests.csproj files from the solution.

**Comment by coderpatros** [comment]
I think it would be good to use the same resolution as `dotnet test` if possible and just pass `--exclude-test-projects` or something like that.

**Comment by coderpatros** [comment]
Hi @cmenzi just wondering what the use case is for this.

I was just thinking, if I wanted to do this for my projects, I would just specify the relevant project.

For example, for CycloneDX I could just generate a BOM for CycloneDX/CycloneDX.csproj. That would exclude test projects as they aren't dependencies.

Just wondering if this is a convenience vs a strong requirement.

**Comment by cmenzi** [comment]
Hi @coderpatros 

The problem is, that we usually have a solution (.sln) file with the following projects:

```
my-service.sln
- my-service.csproj (API)
- my-service.client.csproj (API Client)
- my-service.tests.csproj (Test project)
```

Now, if I just call cyclonedx for the `my-service.csproj`, I don't have the dependencies of the api client project.

Calling it on the solution is also more convenient. :-)

Option 1) Call cyclonedx twice and merge it
Option 2) Treat it as two projects also in dependency-track 
Option 3) Allow to specify `--include` and an `--exclude` 
Option 4) Allow to specify `--exclude-tests`, same like ` -d|--exclude-dev `

**Comment by Bertk** [comment]
Hi,

We also need this feature and prefer a solution like **Option 4** but I am not sure whether a regular expression is the correct solution.

We use project properties to identify test projects e.g.
```xml
  <PropertyGroup>
     <IsTestProject>true</IsTestProject>
     <SonarQubeTestProject>true</SonarQubeTestProject>
  </PropertyGroup>
```

see also ['dotnet test' in solution folder fails when non-test projects are in the solution #1129](https://github.com/Microsoft/vstest/issues/1129)
