### ISSUE TITLE
Github license resolution fails for repos not using "master"

### ISSUE THREAD

**Issue by alitheg** [CycloneDX/cyclonedx-dotnet#432]
As lots of repos have now moved away from calling the default branch "master", this library fails Github license resolution for those libraries now. Perhaps the support ticket referenced in the code will get fixed, but if not it might be worth failing once and trying "main" too.

**Comment by coderpatros** [comment]
Thanks for raising the issue. We should probably be checking what the default branch is first and just using that. I'm starting to work on the next major version. So I'll probably lump it in with that unless someone else wants to create a PR in the meantime.

**Comment by alitheg** [comment]
You know, actually - I was looking deeper into the code so that I could see whether I could tackle a PR for it, and it looks like you just ignore references that aren't `master`, rather than using `master` blindly? 

So that would mean there's still an issue in that it should accept `main` as well (which would be a simple `or` I think?), but it also means the issue I'm seeing (on inspecting my nuspec file) is that the license is specified as `master`, but they've changed their repository to using `main`

**Comment by killi199** [comment]
Main problem could be fixed with: https://github.com/CycloneDX/cyclonedx-dotnet/pull/515. But all other branches besides main and master won't be fixed with that.
