### ISSUE TITLE
Packages included by Directory.Build.props will not be excluded with --exclude-dev

### ISSUE THREAD

**Issue by patspaeth** [CycloneDX/cyclonedx-dotnet#445]
I am using the Arcade Build SDK from microsoft by defining it in the Directory.Build.targets file:
```
<Import Project="Sdk.targets" Sdk="Microsoft.DotNet.Arcade.Sdk" />
```
And 
using analyzers in the Directory.Build.props file:
```
    <ItemGroup Condition="$(BUILD_REASON) == ''">
        <PackageReference Include="SonarAnalyzer.CSharp" Version="8.28.0.36354">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="AsyncFixer" Version="1.5.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SerilogAnalyzer" Version="0.15.0.0" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Nerdbank.GitVersioning" Version="3.4.231">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
    </ItemGroup>
```

I would now assume that these dependencies will be excluded when I use following option: 
```
dotnet-CycloneDX -o SBOM -biop ./artifacts --exclude-dev mySolution.sln
```

__Actual:__
But I see all these dependencies in my BOM file:
Retrieving AsyncFixer 1.5.1
Retrieving Microsoft.Build.Tasks.Git 1.1.0-beta-20206-02
Retrieving Microsoft.SourceLink.AzureRepos.Git 1.1.0-beta-20206-02
Retrieving Microsoft.SourceLink.Common 1.1.0-beta-20206-02
Retrieving Microsoft.SourceLink.GitHub 1.1.0-beta-20206-02
Retrieving Nerdbank.GitVersioning 3.4.231
Retrieving Newtonsoft.Json 13.0.1
Retrieving SerilogAnalyzer 0.15.0
Retrieving GitHub license for repository Suchiman/SerilogAnalyzer and ref master
Retrieving SonarAnalyzer.CSharp 8.28.0.36354
Retrieving XliffTasks 1.0.0-beta.20502.2

__Expected:__
Retrieving Newtonsoft.Json 13.0.1

I have made an example project and appended here
[MySolution.zip](https://github.com/CycloneDX/cyclonedx-dotnet/files/7432669/MySolution.zip)
!

**Comment by Bertk** [comment]
The "**suppressParent**" attribute should be used to remove developer dependencies (see [suppressParent documentation](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets#suppress-parent))

snippet from a Project.asset.json file
```
      "net7.0": {
        "targetAlias": "net7.0",
        "dependencies": {
          "AsyncFixer": {
            "include": "Runtime, Build, Native, ContentFiles, Analyzers",
            "suppressParent": "All",
            "target": "Package",
            "version": "[1.6.0, )",
            "versionCentrallyManaged": true
          },
```

**Comment by Bertk** [comment]
@coderpatros @patspaeth Please close this issue.
