### ISSUE TITLE
dotnet cyclonedx failed | Unable to find package 

### ISSUE THREAD

**Issue by mrrobinhood996** [CycloneDX/cyclonedx-dotnet#449]
Hi,
My current project has import PackageReference from one of the custom in house library. Is it possible to ignore and continue to run dotnet cyclonedx when it can't able to identify/restore the package.
For example: 
PackageReference Include="Serilog.Enrichers.Environment" Version="2.2.0" 
PackageReference Include="**<In-House.Logging>**" Version="2.3.8" 

dotnet cyclonedx will fail while looking into **<In-House.Logging>** library because it it one of my other project that I need to refer to in my current project and it is not part of Nuget Package.

**Comment by mrrobinhood996** [comment]
Can we change line 136 to warning instead of throw error?
![image](https://user-images.githubusercontent.com/93754615/140460398-9ee4d9bb-249b-40f7-b4cc-5ebba3c88da4.png)

**Comment by mrrobinhood996** [comment]
Should I change to ProjectReference when I want to integrate other project into my current project?

**Comment by coderpatros** [comment]
v2.2.0 now has an option to disable restore. Does that solve this problem?
