### ISSUE TITLE
CycloneDX - Dependency Graph displays transitive dependencies with inaccurate version

### ISSUE THREAD

**Issue by VijayB2606** [CycloneDX/cyclonedx-dotnet#453]
Hello,

I have a .NET Core solution which has two projects with below frameworks.

1. netcoreapp3.1
2. netstandard2.0

A] netcoreapp3.1 project -
    In this project, I installed nuget package Automapper@10.1.1. It has two dependencies as below -
    AutoMapper@10.1.1  =>Microsoft.CSharp@4.7.0
                                       => System.Reflection.Emit@4.7.0

B] netstandard2.0 project -
    In this project, I installed nuget package Microsoft.CSharp@4.0.0.

After running CycloneDX v2.2.0 tool against this .NET Core solution, the resultant SBOM shows inaccurate dependency graph.

Refer below images.

<img width="226" alt="NETCore_Solution" src="https://user-images.githubusercontent.com/93205353/141099905-e3b9657c-2518-4441-b356-403de4e3142a.PNG">

<img width="453" alt="DependencyGraph_Issue" src="https://user-images.githubusercontent.com/93205353/141096823-48262fe8-e5a8-4a3c-91aa-bde62bc7ac18.PNG">

In the dependency graph, dependency of Automapper@10.1.1 is displayed as below.
AutoMapper@10.1.1  =>Microsoft.CSharp@4.0.0
                                   => System.Reflection.Emit@4.7.0
Microsoft.CSharp@4.7.0 should be displayed as a dependency and not Microsoft.CSharp@4.0.0.

Also, Microsoft.CSharp@4.0.0 is displayed twice in the dependency graph and Microsoft.CSharp@4.7.0 is not displayed.

Thanks and Regards,
Vijay

**Comment by patspaeth** [comment]
I see the same issue that package dependency versions will be overwritten and causes duplications.
I think this line will cause the error:
https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/CycloneDX/Program.cs#L268
