### ISSUE TITLE
NOASSERTION as LicenseId in generated SBOMs

### ISSUE THREAD

**Issue by mr-zepol** [CycloneDX/cyclonedx-dotnet#525]
When generating SBOM from .csproj files it seems that when the license can be parsed correctly ( its ID), `NOASSERTION` value is added instead, this causes an error when trying to consume the bom (validating) using the cyclonedx-java-core library, it says that that ID is not a valid one which is true since that value is not in the list the library uses.

In this case, maybe the way to proceed would be to ignore that license or not generated the bom?

**Comment by madpah** [comment]
@coderpatros - does `cyclonedx-dotnet` perform schema validation? I'm assuming not based on the above report?

**Comment by mr-zepol** [comment]
@coderpatros are there any plans to solve this issue anytime soon?
