### ISSUE TITLE
Update CONTRIBUTING documentation to require sign-off

### ISSUE THREAD

**Issue by RodneyRichardson** [CycloneDX/cyclonedx-dotnet#538]
There is no mention in [README.md](https://github.com/CycloneDX/cyclonedx-dotnet/blob/master/README.md) or [CONTRIBUTING.md](https://github.com/CycloneDX/.github/blob/master/CONTRIBUTING.md) that commits must be signed off, yet there is a check that prevent pull requests being merged without sign-off.

The documentation should also detail what sign-off actually means, such as a reference to a [Developer Certificate of Origin](https://www.eclipse.org/legal/DCO.php).

**Comment by CodeTigerCloud** [comment]
Wrote a pull request to add a reference to a DCO.

https://github.com/CycloneDX/.github/pull/16
