### ISSUE TITLE
Dependency Graph has duplicates dependencies

### ISSUE THREAD

**Issue by mr-zepol** [CycloneDX/cyclonedx-dotnet#557]
After generating an SBOM we see that the graph has duplicated entries, this seems like a bug because they are the same, so it does not make sense to have them several times. And this is causing some confusion among customers.

For example:

![image](https://user-images.githubusercontent.com/21176019/171231287-75bb10b7-6c64-427e-bf25-93473f985976.png)
![image](https://user-images.githubusercontent.com/21176019/171231319-54833c7d-07d1-4289-98d3-3ca41bb71856.png)

It should have only one entry of each component by level

**Comment by RodneyRichardson** [comment]
Do you also have duplicate components in the SBOM? Or do you have different versions of the same component (e.g. "pkg:nuget/coverlet.collector.3.1.0" and "pkg:nuget/coverlet.collector.3.1.2")?

**Comment by patspaeth** [comment]
#537 should fix that issue (once it is released) @coderpatros
