### ISSUE TITLE
GitHub rate limit exceeded

### ISSUE THREAD

**Issue by AfshinOnline** [CycloneDX/cyclonedx-dotnet#652]
When running Cyclone-DX we get the following error:

GitHub API rate limit exceeded.

@coderpatros Is this a known issue ?

**Comment by mbxsuite** [comment]
you have to provide a github access token. This is not an issue of cyclondx. At least v2.7.0 has parameter therefor.

**Comment by peterkline** [comment]
To follow-up on @mbxsuite comment.  This message is a little confusing because its trying to hit GitHub to resolve license info but if you don't specify the `-gt` flag with your token or you disable lookup by passing `-dgl`

This isn't an defect but rather poor output to what the issue really is
