### ISSUE TITLE
Support for BOM aggregation inside NuGet packages

### ISSUE THREAD

**Issue by tmilnthorp** [CycloneDX/cyclonedx-dotnet#682]
We currently distribute NuGet packages that have a combination of managed and native code. The native code is redistributed via the nupkg in the runtimes directory, and is called via PInvoke. The native code is built utilizing the [Conan package manager](https://conan.io) for C++ dependencies, and we generate a BOM  with [cyclonedx-conan](https://github.com/CycloneDX/cyclonedx-conan).

For the BOM to be complete, we need an aggregate of all of the BOM information for both NuGet as well as the additional BOM information for the native runtimes. Although in our case we're using Conan, this should be tool-agnostic.

I am wondering the best way to support this in cyclonedx-conan. Perhaps we could create a BOM folder inside the nupkg with CycloneDx files inside, that cyclondedx-dotnet could recursively traverse and aggregate?

This seems similar to #79, although slightly different.

**Comment by Bertk** [comment]
Please check the existing CycloneDX tools
- [cyclonedx-cli](https://github.com/CycloneDX/cyclonedx-cli)
- [CyclondeDX Generator](https://github.com/CycloneDX/cdxgen)

**Comment by tmilnthorp** [comment]
@Bertk I am looking for how we can solve the issue of redistributing an aggregated BOM, not how to generate one.

NuGet packages can combine both managed and native code, say using PInvoke. If the native code was generated using Conan for C++ (for instance), simply traversing the NuGet dependency hierarchy will provide a complete picture of the dependencies. One would need to place the aggregate BOM somewhere to provide the additional context.

**Comment by Bertk** [comment]
SBOM management tools are not the scope for this tool project but I would use _bom-ref_ for the C++ component and not use the nuget package for distribution. A URL within the nuget **README.md** could be used to access the SBOM for the nuget project releases.

 - [Dependency graph](https://cyclonedx.org/use-cases/#dependency-graph)
 -

**Comment by CodeTigerCloud** [comment]
I unfortunately don't have an answer to the issue. But the redistributing an aggregated BOM is not a task for the tool that merely generates BOMs from .net-projects. I close this issue.
