### ISSUE TITLE
A Docker container image would make it easier to deal with different runtime versions

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-dotnet#69]
Pretty much what the title says. For situations where you aren't running a current LTS runtime or don't want to worry about what runtime versions are available.

Dockerfile is ready to go here...
https://github.com/coderpatros/cyclonedx-dotnet/blob/docker/Dockerfile

But wanted to gauge your interest first @stevespringett. If you'd prefer not to have another thing to worry about I can just keep it as an unofficial image.

You can find it here (assuming the dockerhub build has finished, they can be slow)...
https://hub.docker.com/r/coderpatros/cyclonedx-dotnet

**Comment by stevespringett** [comment]
Yes, there's interest, but I'll need to incorporate it into the release script, so that it doesn't end up being another thing to manage.

A similar ticket was opened on the Python implementation recently.
https://github.com/CycloneDX/cyclonedx-python/pull/46

**Comment by coderpatros** [comment]
Hmm... interesting idea @stevespringett one container to rule them all. It could get really bloated though. Probably better to have specific containers for each implementation that have a common base so they can be trivially combined as well. 

I still need to tweak my dockerfile I’ll have a think about it first though.

**Comment by coderpatros** [comment]
I’ll change this so it doesn’t rebuild it from scratch but instead takes the output from the build process and installs that nuget package. I’ll also investigate if there could be a way to combine independent docker images and run them interactively via docker compose or something like that. It could get tricky to use unless all implementations can be reliably pointed at a directory. The .net implementation currently can’t be as it only looks for package files for full framework projects.

**Comment by coderpatros** [comment]
Sorry, sort of thinking through this out loud. 

A simpler solution might be a script that you tell what implementations you want to be run that then merges the boms from each?

Just trying to think of what would be the simplest way to get towards the desired outcome.

**Comment by stevespringett** [comment]
I think we are proceeding with a Docker image per implementation. So .NET will have its own, etc.

I'm looking for a simple solution that would work for the majority of users.

**Comment by karolswdev** [comment]
Random guy chipping in - I think it's a great idea to have this tool Dockerized, let me know if I can help in any way.

**Comment by stevespringett** [comment]
Added in 6194dc47e798743274a9607ac991ff63e916d7c0

**Comment by stevespringett** [comment]
Container published to https://hub.docker.com/r/cyclonedx/cyclonedx-dotnet
