### ISSUE TITLE
CycloneDX does not work on .NET Core 7 container

### ISSUE THREAD

**Issue by hschink** [CycloneDX/cyclonedx-dotnet#692]
# General

Version: `2.7.0`
Operating system: Docker container `mcr.microsoft.com/dotnet/sdk:7.0`

# Steps to reproduce

1. Create a docker container and connect to it
    ```bash
    docker run --rm -it --name sdk7 mcr.microsoft.com/dotnet/sdk:7.0
    ```
1. Install CycloneDX
   ```bash
   dotnet tool update --global CycloneDX
   ln -s ~/.dotnet/tools/dotnet-CycloneDX /usr/bin/cyclonedx
   ```
1. Execute CycloneDX
   ```bash
   cyclonedx
   ```

# Expected result

CycloneDX returns the help screen.

# Actal result

CycloneDX returns the following error:
```
You must install or update .NET to run this application.

App: /root/.dotnet/tools/dotnet-CycloneDX
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  7.0.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=debian.11-x64
```

# Note

This seems to be related to #616.

**Comment by hschink** [comment]
Here is a possible workaround by installing .NET Core 6 on the .NET Core 7 SDK image:
```dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0

RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update && apt-get install -y dotnet-sdk-6.0 \
    && rm -rf /var/lib/apt/lists/* \
    && dotnet tool install --global CycloneDX \
    && ln -s /root/.dotnet/tools/dotnet-CycloneDX /usr/bin/CycloneDX
```
This also directly installs CycloneDX.

**Comment by Bertk** [comment]
The current **CycloneDX** tool version **V2.7.0** supports only _.NET Core 3.1_ and _.NET 6_. Microsoft does not support .NET Core 3.1 anymore (out of support since December 13th, 2022).
![image](https://user-images.githubusercontent.com/2315215/236667077-797c356b-0928-43ff-b019-a9b1fbe4ee38.png)

**Comment by pfjason-bbmus** [comment]
> The current **CycloneDX** tool version **V2.7.0** supports only _.NET Core 3.1_ and _.NET 6_. Microsoft does not support .NET Core 3.1 anymore (out of support since December 13th, 2022). ![image](https://user-images.githubusercontent.com/2315215/236667077-797c356b-0928-43ff-b019-a9b1fbe4ee38.png)
> 
> The git master branch has already _.NET 6_ and _.NET 7_ support and the next release of **CycloneDX** tool will resolve the issue.

When can we expect a release, even a pre-release named version that can be installed with the dotnet tool? 2.7.0 was November '22, but there were many releases in November and October of last year and none since.

**Comment by hschink** [comment]
This is solved with the latest release.

**Comment by hschink** [comment]
@Bertk [Just did an hour ago](https://github.com/CycloneDX/cyclonedx-dotnet/issues/692#issuecomment-1710119679). Did I miss something.

**Comment by Bertk** [comment]
No, The issue is closed. Thanks
