### ISSUE TITLE
Include ProjectReference in output

### ISSUE THREAD

**Issue by MrGrando** [CycloneDX/cyclonedx-dotnet#703]
We have an application that is physically divided into many DLLs (typically matching the logical layers) 
So the solution consists of the project for the main executable, with project references to the projects that produces DLLs. But the DLLs are not published as NuGet packages (For sure we have a lot of reference to NuGet packages as well)

The BOM we need to produce must include also the DLLs that are "internal DLLs' (e.g. are included as ProjectReference in the solution file).  

For what I can tell it is not possible to get ProjectReferences DLL in the output BOM

Any package that is referred to from a ProjectReferences project will however end up in the BOM and is listed as a dependency 
directly to the executable.

Any hints, tricks or thoughts?

//MG

**Comment by Bertk** [comment]
Hi, you can generate independent SBOMs for **library** but you ship an **application** and the SBOM will not have references for the your project DLLs.  Maybe using a tool which merges all library SBOMs and the application SBOM will solve your issue.

> BOM metadata component type: <Application|Container|Device|File|Firmware|Framework|Library|Null|OperationSystem>

**Comment by CodeTigerCloud** [comment]
See #785

**Comment by mtsfoni** [comment]
Check out the new release:
https://github.com/CycloneDX/cyclonedx-dotnet/releases/tag/v3.0.0
