### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by mieliespoor** [CycloneDX/cyclonedx-dotnet#709]
When is the next release planned? 

Can the releasing be automated using actions in Github? Last release was near 7 months back and a long list of changes has since been merged in, some of which fairly important.

**Comment by mieliespoor** [comment]
@coderpatros any feedback?

**Comment by mieliespoor** [comment]
@coderpatros @stevespringett can we please get some form of traction on this repo?

**Comment by coderpatros** [comment]
I'm working on getting a new release this week.
