### ISSUE TITLE
dotnet list package vulnerable support

### ISSUE THREAD

**Issue by MarcosxDeveloper** [CycloneDX/cyclonedx-dotnet#715]
Ref: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package

**Comment by Bertk** [comment]
Sorry, could you please add some information why `dotnet list package` is an **issue**.
> cyclonedx-dotnet creates CycloneDX Software Bill of Materials (SBOM) from .NET Projects

**Comment by CodeTigerCloud** [comment]
Probably wants us to make use of the --vulnerable argument. Anyway, that's not the purpose of this project.
