### ISSUE TITLE
Include Subproject in hierarchy

### ISSUE THREAD

**Issue by rkg-mm** [CycloneDX/cyclonedx-dotnet#730]
When scanning a .sln or scanning a .csproj which references other .csproj, the bom is generated fine, but the dependency-tree does not include the name from which subproject a dependency is coming.
For tools like Dependency-Track, that are used to manage vulnerabilities of the dependencies, it would be nice to see in which project part(s) the dependency is referenced.

Maybe this could be enabled by a config switch to not break existing behaviour

**Comment by CodeTigerCloud** [comment]
See #785

**Comment by mtsfoni** [comment]
Check out the new release:
https://github.com/CycloneDX/cyclonedx-dotnet/releases/tag/v3.0.0
