### ISSUE TITLE
Multiple versions of same package in BOM

### ISSUE THREAD

**Issue by wazzamatazz** [CycloneDX/cyclonedx-dotnet#746]
Say you have a solution with 3 projects (2 class libraries and a console app) and each project references a different version of the same package e.g. the class libraries reference Newtonsoft.Json @ 12.0.1 and 11.0.1 respectively, and the console app references it @ 13.0.3. The console app also references both class libraries.

When building the BOM for the console app (e.g. `dotnet tool run dotnet-CycloneDX './MyApp/MyApp.csproj' -o './bom' -r`), the resulting BOM contains entries for all three versions of Newtonsoft.Json, instead of just the version that is actually selected at compile time when building the console app.

Is this the intended behaviour? I can kind of understand the reasoning if it is since the BOM is being generated with the `-r` flag, but it's also quite confusing because the earlier versions are not part of the final bill of materials for the project that CycloneDX is being run against. The behaviour has caused us some confusion when a BOM is imported into Dependency-Track and we start receiving package vulnerability notifications even though the project that the BOM was built for is already referencing a version that mitigates the issue.

**Comment by CodeTigerCloud** [comment]
I understand that with the current way CycloneDX .NET resolves the dependencies, it is not easily possible to know which assembly will be used in the final product.

See also #399
