### ISSUE TITLE
DLLs missing from SBOM

### ISSUE THREAD

**Issue by ag-lls** [CycloneDX/cyclonedx-dotnet#756]
Hi there, 

is it possible for the tool to include DLLs that are listed in the projects references?
Not all of our used libraries are available as NuGet Packages, so as of right now it seems our SBOM would be incomplete, since the DLLs are not listed.

**Comment by CodeTigerCloud** [comment]
So far, that's not possible. You can manually maintain them in another BOM and then combine them using [CycloneDX cli's](https://github.com/CycloneDX/cyclonedx-cli) merge function.

See also #79

**Comment by CodeTigerCloud** [comment]
Linked to #785

**Comment by mtsfoni** [comment]
Check out the new release:
https://github.com/CycloneDX/cyclonedx-dotnet/releases/tag/v3.0.0
