### ISSUE TITLE
Call via dotnet cyclonedx .... doesn't pass shortname parameter -d to cyclonedx

### ISSUE THREAD

**Issue by mtsfoni** [CycloneDX/cyclonedx-dotnet#760]
> Wow.... I'm in utter disbelief, but it appears to me, that the call `dotnet cyclonedx ...` does not forward the -d parameter to the actual application. While calling the .exe in the traditional style works fine. I could reproduce this behaviour on a 2nd device.
> 
> That was the reason that my boms included the library despite the -d option. I can only assume that dotnet reserves -d for something and doesn't forward it. I'd like if somebody else could confirm my observation (I almost lost my sanity figuring this out).
> 
> We probably should change the parameter shortname or add a second shortname to stay downwards compatible.
> 

_Originally posted by @CodeTigerCloud in https://github.com/CycloneDX/cyclonedx-dotnet/issues/665#issuecomment-1722307158_

This can be a very frustrating bug for users until they find out. The workaround is to use the long version `--exclude-dev`.

I think best is to fix it by changing it to -ed, however that would be a breaking change and would require a new major version.

**Comment by Bertk** [comment]
Please check also short form of other parameters. There are no naming convention but at least some of the parameters could be harmonized with other tools.

- -o for --output
- -v for --verbosity
- -f for --framework
- -r for --runtime


see https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax?source=recommendations#short-form-aliases
