### ISSUE TITLE
Discuss inviting @coderpatros to team

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-dotnet#85]
@coderpatros With all of your contributions (and two more PR's possibly ready for merge?), I'm wondering if it would make sense to invite you to the team, which would provide more direct access to the repos, ability to merge PRs, etc. 

Let me know if this is something you're interested in. If not, no worries. We can continue collaborating the way we have been. Your call.

**Comment by coderpatros** [comment]
Hi @stevespringett definitely interested.

**Comment by stevespringett** [comment]
Complete. You should be a maintainer of the this repo now. In the future, it will be across all repos. Let me know if you experience any permission issues.
