### ISSUE TITLE
Inconsistent Timestamp Representation in XML and JSON BOM Files

### ISSUE THREAD

**Issue by eugenhoffmann** [CycloneDX/cyclonedx-dotnet#877]
I have noticed that the timestamp representation in the XML and JSON BOM files is inconsistent. While both formats are ISO 8601 conform, the XML BOM file contains a timestamp with a precision of up to 7 decimal places for the seconds fraction:

- XML: 2024-05-17T15:50:31.6823708+00:00
- JSON: 2024-05-17T15:50:31Z

In my opinion, this level of precision is not necessary. Furthermore, the second fractions more than 3 digits are not supported by the Python API [datetime.fromisoformat(date_string)](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat) method.

While these differences are not incorrect, they can be confusing and may cause issues when processing the data. I would like to propose that we adopt a consistent timestamp representation across both file formats, ideally using the JSON timestamp format.

Thank you for considering this issue!

**Comment by mtsfoni** [comment]
This is most likely an issue for the [CycloneDX dotnet library](https://github.com/CycloneDX/cyclonedx-dotnet-library/issues) where the serialization actually happens.

Could you open this issue also there?
Once fixed in the library, I will create a new version of the generating tool.

**Comment by eugenhoffmann** [comment]
Thank you for your response. I have opened an [Issue](https://github.com/CycloneDX/cyclonedx-dotnet-library/issues/298) in the CycloneDX dotnet library as suggested

**Comment by mtsfoni** [comment]
Should be resolved in 3.0.7. Let me know if you still have problems
