### ISSUE TITLE
CycloneDX should fail when the provided project file was not found

### ISSUE THREAD

**Issue by DerGary** [CycloneDX/cyclonedx-dotnet#882]
Current Behavior:
It does not fail:
![image](https://github.com/CycloneDX/cyclonedx-dotnet/assets/4302467/71dababa-070a-4490-8771-a081b93d5b8e)

Expected Behavior:
The exit code is different to 0 or anything is printed on stderr

**Comment by mtsfoni** [comment]
Totally right.

I need to test my PR and might release a new version tonight.

**Comment by DerGary** [comment]
Nice, thanks for this fast reaction 👍

**Comment by mtsfoni** [comment]
fixed in 3.0.8
