### ISSUE TITLE
Add support for X# Project files

### ISSUE THREAD

**Issue by VolkmarR** [CycloneDX/cyclonedx-dotnet#895]
CycloneDX-DotNet currently supports project files with the extensions .csproj, .fsproj and .vbproj. It would be nice to add support for the .xsproj extension. This extension is used by project files for [x#](https://xsharp.eu/), an open source development language for .NET, based on the xBase language.

I already made some tests and after adding the extension to the allowed extensions, CycloneDX-DotNet successfully produced the SBOM file.

I can provide a pull request with the necessary change, documentation and tests.

**Comment by mtsfoni** [comment]
Is .xsproj the exact same format as .csproj and is also built via dotnet build using NuGet?
Then I see no problem and await your PR 😊
