### ISSUE TITLE
CVE in System.Text.Json 7.0.2 and System.Formats.Asn1

### ISSUE THREAD

**Issue by MarioAllegro** [CycloneDX/cyclonedx-dotnet#906]
There are two packages currently used in cyclone dx which are preventing us to build new images and should be updated.

<PackageVersion Include="System.Formats.Asn1" Version="8.0.1" />
<PackageVersion Include="System.Text.Json" Version="8.0.4" />

Could I somehow create a PR to fix it or are you ready to fix it by yourself

**Comment by mtsfoni** [comment]
Hi, a PR is welcome. I will look into this matter later today.

**Comment by MarioAllegro** [comment]
Here is the PR: https://github.com/CycloneDX/cyclonedx-dotnet/pull/907
Hope I did get all right. Tests are running again

**Comment by mtsfoni** [comment]
Merged and released
