### ISSUE TITLE
Make github license lookup optional

### ISSUE THREAD

**Issue by sebgamby** [CycloneDX/cyclonedx-dotnet#96]
My organisation only produces software for in-house usage so we are not liable for license infringement. Furthermore, the github lookup is bothersome because our build servers are not supposed to have a direct Internet access, we must edit our firewall rules because of that. Is it possible to make this lookup optional?

**Comment by coderpatros** [comment]
@sebgamby sounds like a pretty reasonable use case to me.

**Comment by coderpatros** [comment]
@sebgamby I've created PR #97 for this.

Any chance you could do a custom build based on the branch [optional-licence-resolution](https://github.com/CycloneDX/cyclonedx-dotnet/tree/optional-licence-resolution) and test it out in your environment before I merge the change?

**Comment by sebgamby** [comment]
@coderpatros Thanks a lot for the quick reply. I have tested it and it seems to work fine. When providing the "-dgl" argument, I no longer see the calls to GitHub in the console log. The firewall is currently open on the build servers so I cannot be 100% sure that no calls are being made to GitHub but is close enough.

**Comment by sebgamby** [comment]
I have deployed the modified tool so for me the issue is solved. Feel free to merge the PR when it suits you.

**Comment by coderpatros** [comment]
Thanks for confirming @sebgamby

**Comment by oxdef** [comment]
@coderpatros Thanks for fixing this issue. When do you plan to update CycloneDX NuGet package so everyone can use the new option?

**Comment by stevespringett** [comment]
0.9.3 has been pushed to NuGet
