### ISSUE TITLE
dotnet Cyclonedx 0.9.2 version gave error

### ISSUE THREAD

**Issue by aykutaricioglu** [CycloneDX/cyclonedx-dotnet#98]
Hello,

Dotnet CycloneDx gave the following error. It try to look at "C:\Users\steve\..". Could you review that?

**Comment by coderpatros** [comment]
Could you please share with me the dependencies for your project?

**Comment by aykutaricioglu** [comment]
Hello,

Our project is very big. Packages are not together.

![Screen Shot 2020-03-19 at 11 38 30](https://user-images.githubusercontent.com/9120266/77047738-52b91300-69d6-11ea-9e24-bd7ad2ede5bc.png)
![Screen Shot 2020-03-19 at 11 38 43](https://user-images.githubusercontent.com/9120266/77047748-56e53080-69d6-11ea-96a3-c57cdeaab5dc.png)

**Comment by aykutaricioglu** [comment]
Hello again,

I tried to scan submodule in this project. It gave same error.

![Screen Shot 2020-03-19 at 11 56 01](https://user-images.githubusercontent.com/9120266/77049251-cc520080-69d8-11ea-8852-4951dea4524f.png)


![Screen Shot 2020-03-19 at 11 55 42](https://user-images.githubusercontent.com/9120266/77049247-ca883d00-69d8-11ea-9304-993076eb5aa2.png)

**Comment by coderpatros** [comment]
@aykutaricioglu any chance you can copy and paste those dependencies as text so I can try and reproduce this myself.

**Comment by aykutaricioglu** [comment]
<?xml version="1.0" encoding="utf-8"?>

<packages>

  <package id="AntiXSS" version="4.3.0" targetFramework="net452" />

  <package id="Antlr.Runtime" version="2.7.6" targetFramework="net452" />

  <package id="BouncyCastle.Crypto" version="1.3.0.1" targetFramework="net452" />

  <package id="COMM.CommonTypes" version="1.1.59" targetFramework="net472" />

  <package id="EntityFramework" version="6.1.2" targetFramework="net452" />

  <package id="EntityFramework.Extended" version="6.1.0.168" targetFramework="net452" />

  <package id="evopdf" version="4.6" targetFramework="net452" />

  <package id="Microsoft.ApplicationServer.Caching.Client" version="1.0.0" targetFramework="net452" />

  <package id="Microsoft.ApplicationServer.Caching.Core" version="1.0.0" targetFramework="net452" />

  <package id="Newtonsoft.Json" version="4.5.8" targetFramework="net452" />

  <package id="Oracle.ManagedDataAccess" version="12.2.1100" targetFramework="net452" />

  <package id="Oracle.ManagedDataAccess.EntityFramework" version="12.2.1100" targetFramework="net452" />

  <package id="Smart.log4net" version="1.2.13.0" targetFramework="net452" />

  <package id="Smart.VeriBranch.Authorization" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.ApprovalManagement" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.Common" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.Managers" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.Transactions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.Constants" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.CustomExpressions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.Exceptions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.Expressions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.MessageDefinitions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Core" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.DataAccess" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Integration.Proxy" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.IntegrationCore" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.CommonHelper" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.ConfigurationUtilities" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.Diagnostics" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.Extensions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.ResourceUtilities" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.Security" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.XmlSerialization" version="1.1.52" targetFramework="net472" />

  <package id="SpreadsheetGear" version="6.0.3" targetFramework="net452" />

</packages>

**Comment by aykutaricioglu** [comment]
`<?xml version="1.0" encoding="utf-8"?>

<packages>

  <package id="AntiXSS" version="4.3.0" targetFramework="net452" />

  <package id="Antlr.Runtime" version="2.7.6" targetFramework="net452" />

  <package id="BouncyCastle.Crypto" version="1.3.0.1" targetFramework="net452" />

  <package id="COMM.CommonTypes" version="1.1.59" targetFramework="net472" />

  <package id="EntityFramework" version="6.1.2" targetFramework="net452" />

  <package id="EntityFramework.Extended" version="6.1.0.168" targetFramework="net452" />

  <package id="evopdf" version="4.6" targetFramework="net452" />

  <package id="Microsoft.ApplicationServer.Caching.Client" version="1.0.0" targetFramework="net452" />

  <package id="Microsoft.ApplicationServer.Caching.Core" version="1.0.0" targetFramework="net452" />

  <package id="Newtonsoft.Json" version="4.5.8" targetFramework="net452" />

  <package id="Oracle.ManagedDataAccess" version="12.2.1100" targetFramework="net452" />

  <package id="Oracle.ManagedDataAccess.EntityFramework" version="12.2.1100" targetFramework="net452" />

  <package id="Smart.log4net" version="1.2.13.0" targetFramework="net452" />

  <package id="Smart.VeriBranch.Authorization" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.ApprovalManagement" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.Common" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.Managers" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Business.Transactions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.Constants" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.CustomExpressions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.Exceptions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.Expressions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Common.MessageDefinitions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Core" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.DataAccess" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Integration.Proxy" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.IntegrationCore" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.CommonHelper" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.ConfigurationUtilities" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.Diagnostics" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.Extensions" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.ResourceUtilities" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.Security" version="1.1.52" targetFramework="net472" />

  <package id="Smart.VeriBranch.Utilities.XmlSerialization" version="1.1.52" targetFramework="net472" />

  <package id="SpreadsheetGear" version="6.0.3" targetFramework="net452" />

</packages>`

**Comment by aykutaricioglu** [comment]
[packages.config.zip](https://github.com/CycloneDX/cyclonedx-dotnet/files/4354142/packages.config.zip)

**Comment by coderpatros** [comment]
Thanks for that @aykutaricioglu 

I can generate a bom from that packages.config file without issue.

Is there anything interesting about your environment? Restricted DNS resolution, restrictive network proxy, etc?

**Comment by aykutaricioglu** [comment]
Thank you for your help. We solved this link.

**Comment by coderpatros** [comment]
@aykutaricioglu do you mind sharing what the cause was? It would be helpful to know.
